Emlaksite/Models/Ilan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Emlaksite.Models
{
	public class Ilan
	{
		[Key]
        public int IlanID { get; set; }

		public string Açıklama { get; set; }
		public double Fiyat { get; set; }
		public int OdaSayisi { get; set; }
		public int BanyoSayisi { get; set; }
		public bool Kredi { get; set; }		
		public int Alan { get; set; }
		public string Kat { get; set; }
		public string Telefon { get; set; }
		public string Adres { get; set; }
		public string UserName { get; set; }
		public int SehirID { get; set; }
		public int SemtID { get; set; }
		public int DurumID { get; set; }
		public int MahalleID { get; set; }
		public Mahalle Mahalle { get; set; }
		public int TipID { get; set; }
		public Tip Tip { get; set; }
        public List<Resim> Resims { get; set; }
    }
}

Emlaksite/Controllers/IlanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlaksite.Models;

namespace Emlaksite.Controllers
{
    public class IlanController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Ilan
        public ActionResult Index()
        {
            // var ilans = db.Ilans.Include(i => i.Mahalle).Include(i => i.Tip);
            var username = User.Identity.Name;
			var ilans = db.Ilans.Where(i=>i.UserName==username).Include(i => i.Mahalle).Include(i => i.Tip);
			return View(ilans.ToList());
        }
      
        public List<Sehir> SehirGetir()
        {
            List<Sehir> sehirler = db.Sehirs.ToList();
            return sehirler;
        }
        public ActionResult SemtGetir(int sehirID)
        {
            List<Semt> semtlist = db.Semts.Where(m => m.SehirID == sehirID).ToList();
            ViewBag.semtlistesi = new SelectList(semtlist, "SemtID","SemtAd");
            return PartialView("SemtPartial");
        }
        public ActionResult MahalleGetir(int semtID)
        {
            List<Mahalle> mahallelist = db.Mahalles.Where(m=>m.SemtID==semtID).ToList();
            ViewBag.mahallelistesi = new SelectList(mahallelist, "MahalleID", "MahalleAd");
            return PartialView("MahallePartial");

        }
        public ActionResult ResimEkle(int id)
        {
            var ilanimg = db.Ilans.Where(s => s.IlanID == id).ToList();
            var resimler = db.Resims.Where(s => s.IlanID ==id).ToList();
            ViewBag.IlanResim = ilanimg;
            ViewBag.Resimler = resimler;

            return View();
        }
        [HttpPost]
        public ActionResult ResimEkle(int id,HttpPostedFileBase file)
        {
            string path = Path.Combine("/Content/images/" + file.FileName);
            file.SaveAs(Server.MapPath(path));
            Resim rsm = new Resim();
            rsm.ResimAd = file.FileName.ToString();
            rsm.IlanID = id;
            db.Resims.Add(rsm);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

		public List<Durum> DurumGetir()
        {
            List<Durum> durumlist = db.Durums.ToList();
            return durumlist;
        }
        public ActionResult TipGetir(int durumID)
        {
            List<Tip> tiplist = db.Tips.Where(x => x.DurumID == durumID).ToList();
            ViewBag.tiplistesi = new SelectList(tiplist, "TipID", "TipAd");
            return PartialView("TipPartial");
        }
        // GET: Ilan/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // GET: Ilan/Create
        public ActionResult Create()
        {
            ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirID", "SehirAd");
            ViewBag.durumlist = new SelectList(DurumGetir(), "DurumID", "DurumAd");
            return View();
        }

        // POST: Ilan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IlanID,Açıklama,Fiyat,OdaSayisi,BanyoSayisi,Kredi,Alan,Kat,Telefon,Adres,UserName,SehirID,SemtID,DurumID,MahalleID,TipID")] Ilan ilan)
        {
            if (ModelState.IsValid)
            {
                ilan.UserName = User.Identity.Name;
                db.Ilans.Add(ilan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirID", "SehirAd");			
			ViewBag.durumlist = new SelectList(DurumGetir(), "DurumID", "DurumAd");
			return View(ilan);
        }

        // GET: Ilan/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
			ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirID", "SehirAd");
			ViewBag.durumlist = new SelectList(DurumGetir(), "DurumID", "DurumAd");
			ViewBag.MahalleID = new SelectList(db.Mahalles, "MahalleID", "MahalleAd", ilan.MahalleID);
			ViewBag.SemtID = new SelectList(db.Semts, "SemtID", "SemtAd", ilan.SemtID);
			ViewBag.TipID = new SelectList(db.Tips, "TipID", "TipAd", ilan.TipID);
            return View(ilan);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IlanID,Açıklama,Fiyat,OdaSayisi,BanyoSayisi,Kredi,Alan,Kat,Telefon,Adres,UserName,SehirID,SemtID,DurumID,MahalleID,TipID")] Ilan ilan)
        {
            if (ModelState.IsValid)
            {
                ilan.UserName = User.Identity.Name;
                db.Entry(ilan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
			ViewBag.sehirlist = new SelectList(SehirGetir(), "SehirID", "SehirAd");
			ViewBag.durumlist = new SelectList(DurumGetir(), "DurumID", "DurumAd");		
            return View(ilan);
        }

        // GET: Ilan/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ilan ilan = db.Ilans.Find(id);
            if (ilan == null)
            {
                return HttpNotFound();
            }
            return View(ilan);
        }

        // POST: Ilan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ilan ilan = db.Ilans.Find(id);
            db.Ilans.Remove(ilan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Emlaksite/Views/Ilan/Create.cshtml
@model Emlaksite.Models.Ilan

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Açıklama,"Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Açıklama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Açıklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fiyat,"Fiyat", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OdaSayisi,"Oda Sayısı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.OdaSayisi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OdaSayisi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BanyoSayisi,"Banyo Sayısı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.BanyoSayisi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BanyoSayisi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kredi,"Kredi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            <div class="checkbox">
                @Html.EditorFor(model => model.Kredi)
                @Html.ValidationMessageFor(model => model.Kredi, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Alan,"Alan", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Alan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Alan, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Kat,"Kat" ,htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Kat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Kat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefon,"Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adres,"Adres", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName,"Kullancı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SehirID,"Şehir", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @if (ViewBag.sehirlist != null)
            {
                @Html.DropDownListFor(model => model.SehirID, ViewBag.sehirlist as SelectList, "Şehir Seç", new { @class = "form-control" })
            }
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SemtID,"Semt", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">           
            @Html.DropDownListFor(model => model.SemtID, new SelectList(""), "Semt sec", new { @class = "form-control" })

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MahalleID, "Mahalle", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">          
            @Html.DropDownListFor(model => model.MahalleID, new SelectList(""), "Mahalle sec", new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DurumID, "Durum",htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
            @if (ViewBag.durumlist != null)
            {
                @Html.DropDownListFor(m => m.DurumID, ViewBag.durumlist as SelectList,"Durum Seç", new { @class = "form-control" })
            }
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TipID, "Tip", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-4">
           
            @Html.DropDownListFor(model => model.TipID, new SelectList(""), "Tip Seç", new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-4">
            <input type="submit" value="İlan oluştur" class="btn btn-success" />
            @Html.ActionLink("İlan listesi", "Index", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#SehirID").change(function () {
            var sehirID = $(this).val();
            //debugger
            $.ajax({
                type:"Post",
                url:"/Ilan/SemtGetir?SehirID=" + sehirID,
                contentType:"html",
                success: function (response) {
                    //debugger
                    $("#SemtID").empty();
                    $("#SemtID").append(response);
                }
            })

        })
    })
</script>
<script>
    $(document).ready(function () {
        $("#SemtID").change(function () {
            var semtID= $(this).val();
            //debugger
            $.ajax({
                type:"Post",
                url:"/Ilan/MahalleGetir?SemtID=" + semtID,
                contentType:"html",
                success: function (response) {
                    //debugger
                    $("#MahalleID").empty();
                    $("#MahalleID").append(response);
                }
            })

        })
    })
</script>
<script>
    $(document).ready(function () {
        $("#DurumID").change(function () {
            var durumID = $(this).val();
            //debugger
            $.ajax({
                type:"Post",
                url:"/Ilan/TipGetir?DurumID=" + durumID,
                contentType:"html",
                success: function (response) {
                    //debugger
                    $("#TipID").empty();
                    $("#TipID").append(response);
                }
            })

        })
    })
</script>

Emlaksite/Views/Ilan/Delete.cshtml
@model Emlaksite.Models.Ilan

@{
    ViewBag.Title = "Delete";
}


<div class="container">

<div>
    <h3>bu kaydı silmek istediğnizden emin misiniz=</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
         Mahalle ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MahalleID)
        </dd>

        <dt>
        Tip
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tip.TipAd)
        </dd>

        <dt>
           Açıklama
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Açıklama)
        </dd>

        <dt>
            Fiyat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
           Oda Sayısı
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaSayisi)
        </dd>

        <dt>
          Banyo sayısı
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BanyoSayisi)
        </dd>

        <dt>
          Krediye uygun mu
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kredi)
        </dd>

        <dt>
            Alan
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alan)
        </dd>

        <dt>
            Kat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
         Kullanıcı adı 
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SehirID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SehirID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SemtID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemtID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DurumID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DurumID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a href="/Ilan/Index"><input type="submit" value="İlan lisatesi" class="btn btn-success" /></a>
</div>
    }
</div>
    </div>

Emlaksite/Views/Ilan/Details.cshtml
@model Emlaksite.Models.Ilan

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ilan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Mahalle.MahalleAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mahalle.MahalleAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tip.TipAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tip.TipAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Açıklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Açıklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OdaSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OdaSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BanyoSayisi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BanyoSayisi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kredi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kredi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SehirID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SehirID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SemtID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SemtID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DurumID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DurumID)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IlanID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Emlaksite/Views/Ilan/Index.cshtml
@model IEnumerable<Emlaksite.Models.Ilan>

@{
    ViewBag.Title = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-4 control-label">En az</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En az(Fiyat)">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-4 control-label">En çok</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="En Çok(Fİyat)">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputPassword3" class="col-sm-4 control-label">Şehir</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Şehir">
                    </div>
                </div>
                <div class="form-group">
                    <label for="text" class="col-sm-4 control-label">Semt</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Semt">
                    </div>
                </div>
                <div class="form-group">
                    <label for="text" class="col-sm-4 cont-label">Durum</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Durum">
                    </div>
                </div>
                <div class="form-group">
                    <label for="text" class="col-sm-4 control-label">Tip</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" placeholder="Tip">
                    </div>
                </div>
                <div class="form-group">
                    <label for="text" class="col-sm-4 control-label"></label>
                    <div class="col-sm-6">
                        <button imgtype="submit" class="btn btn-primary"><i class="bi bi-search"></i>Filtreleme</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-9">

            <div class="thumbnail" style="width:845px">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item" aria-current="page"><a href="/Home/Index">Anasayfa</a></li>
                        <li class="breadcrumb-item active" aria-current="page">İlan</li>
                    </ol>
                </nav>
                <a href="/Ilan/Create" class="btn btn-primary btn-block">İlan oluştur</a>
                <table class="table">
                    <tr>
                        <th>
                            Şehir Adı
                        </th>
                        <th>
                            Semt Adı
                        </th>
                        <th>
                            Mahalle Adı
                        </th>
                        <th>Tip</th>
                        <th>Durum</th>                   
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.Sehir.SehirAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.Semt.SemtAd)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.Mahalle.MahalleAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.TipAd)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Tip.Durum.DurumAd)
                            </td>          -
                            <td>
                                <a href="/Ilan/Edit/@item.IlanID" class="btn btn-primary" style="color:white"><i class="fa fa-edit" aria-hidden="true"></i>Güncelle</a>|
                                <a href="/Ilan/ResimEkle/@item.IlanID" class="btn btn-warning">Resim ekle</a> |
                                <a href="/Ilan/Delete/@item.IlanID" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i>Sil</a>
                            </td>
                        </tr>
                    }

                </table>




            </div>

        </div>

    </div>
</div>

Emlaksite/Views/Ilan/ResimEkle.cshtml
@{
    ViewBag.Title = "ResimEkle";
}

<div class="container">

    @using (Html.BeginForm("ResimEkle", "Ilan", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
       
        <div class="form-group">
            @foreach (var item in ViewBag.IlanResim)
            {
            <h3>
                @item.IlanID numaralı için resim ekle</h3>
            <table>
                <tr>
                    <td>Resim Seç</td>
                    <td><input type="hidden" name="id" value="@item.IlanID" /></td>
                    <td><input type="file" name="file"></td>
                    <td><input type="submit" value="Kayıt et" class="btn btn-primary"></td>
                </tr>
            </table>
            }
            </div>

   }

        </div>
        <br />
        <div class="row">
            @foreach (var item in ViewBag.Resimler)
            {
                <div class="col-md-4">
                    <div class="thumbnail">
                        <img src="~/Content/images/@item.ResimAd" height="500" width="500">
                    </div>
                </div>
            }
        </div>