Emlaksite/Controllers/DurumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlaksite.Models;

namespace Emlaksite.Controllers
{
    public class DurumController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Durum
        public ActionResult Index()
        {
            return View(db.Durums.ToList());
        }

        // GET: Durum/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Durum durum = db.Durums.Find(id);
            if (durum == null)
            {
                return HttpNotFound();
            }
            return View(durum);
        }

        // GET: Durum/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Durum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DurumID,DurumAd")] Durum durum)
        {
            if (ModelState.IsValid)
            {
                db.Durums.Add(durum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(durum);
        }
        
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Durum durum = db.Durums.Find(id);
            if (durum == null)
            {
                return HttpNotFound();
            }
            return View(durum);
        }

        // POST: Durum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DurumID,DurumAd")] Durum durum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(durum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(durum);
        }

        // GET: Durum/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Durum durum = db.Durums.Find(id);
            if (durum == null)
            {
                return HttpNotFound();
            }
            return View(durum);
        }

        // POST: Durum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Durum durum = db.Durums.Find(id);
            db.Durums.Remove(durum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
		public PartialViewResult Durumlist()
		{
            var durumlist = db.Durums.ToList();
			return PartialView(durumlist);
		}
		public ActionResult DurumlistSatılıkilanlar(int id)
		{
			var ilan = db.Ilans.Where(i => i.DurumID == id).Include(m => m.Mahalle).Include(e => e.Tip).ToList();
			int index = 0;
			for (int i = 0; i < ilan.Count; i++)
			{
				List<Resim> resimler = new List<Resim>();
				var _ilan = ilan[i];
				index = ilan.FindIndex(f => f.IlanID == _ilan.IlanID);
				var image = db.Resims.Where(w => w.IlanID == _ilan.IlanID).FirstOrDefault();
				resimler.Add(image);
				ilan[index].Resims = resimler;
			}
			return View(ilan.ToList());
		}
		protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Emlaksite/Controllers/TipController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Emlaksite.Models;

namespace Emlaksite.Controllers
{
    public class TipController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Tip
        public ActionResult Index()
        {
            var tips = db.Tips.Include(t => t.Durum);
            return View(tips.ToList());
        }
       
        public PartialViewResult DurumKiralıkMetni()
        {
            var durumkiralık = db.Durums.Where(i => i.DurumID == 3).FirstOrDefault();
            return PartialView(durumkiralık);
        }
		
		public PartialViewResult DurumSatılıkMetni()
        {
            var durumsatılık = db.Durums.Where(i => i.DurumID == 4).FirstOrDefault();
            return PartialView(durumsatılık);
        }
        public ActionResult Satılıkilanlar(int id)
        {

			var ilan = db.Ilans.Where(i=>i.TipID==id).Include(m => m.Mahalle).Include(e => e.Tip).ToList();
			int index = 0;
			for (int i = 0; i < ilan.Count; i++)
			{
				List<Resim> resimler = new List<Resim>();
				var _ilan = ilan[i];
				index = ilan.FindIndex(f => f.IlanID == _ilan.IlanID);
				var image = db.Resims.Where(w => w.IlanID == _ilan.IlanID).FirstOrDefault();
				resimler.Add(image);
				ilan[index].Resims = resimler;
			}
			return View(ilan.ToList());
			
		}

		////Bence burası durum kontrollırında oluşturulması gerekir
		public PartialViewResult DurumTipSatilikPartial()//Satılık ev arsa rezidans isimlerini getiriyoruz
		{
			var durum1 = db.Tips.Where(i => i.DurumID == 4).ToList();
			return PartialView(durum1.ToList());
		}
		public PartialViewResult DurumTipKiralikPartial()//Satılık ev arsa rezidans isimlerini getiriyoruz
		{
			var durum1 = db.Tips.Where(i => i.DurumID == 3).ToList();
			return PartialView(durum1.ToList());
		}
        public PartialViewResult DurumAd1()//Kiralık yazzısı
        {
			var durum1 = db.Durums.Where(i => i.DurumID == 3).FirstOrDefault();
			return PartialView(durum1);
		}
        public PartialViewResult DurumAd2()//Satılık yazısı
        {
			var durum2 = db.Durums.Where(i => i.DurumID == 4).FirstOrDefault();
			return PartialView(durum2);
		}
		//public PartialViewResult DurumTipPartial2()//Kiralık ev arsa rezidans isimlerini getiriyoruz
		//{
		//	var durum1 = db.Tips.Where(i => i.DurumID == 3).ToList();
		//	return PartialView(durum2);
		//}

		// GET: Tip/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // GET: Tip/Create
        public ActionResult Create()
        {
            ViewBag.DurumID = new SelectList(db.Durums, "DurumID", "DurumAd");
            return View();
        }

        // POST: Tip/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TipID,TipAd,DurumID")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Tips.Add(tip);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DurumID = new SelectList(db.Durums, "DurumID", "DurumAd", tip.DurumID);
            return View(tip);
        }

        // GET: Tip/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            ViewBag.DurumID = new SelectList(db.Durums, "DurumID", "DurumAd", tip.DurumID);
            return View(tip);
        }

        // POST: Tip/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TipID,TipAd,DurumID")] Tip tip)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tip).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.DurumID = new SelectList(db.Durums, "DurumID", "DurumAd", tip.DurumID);
            return View(tip);
        }

        // GET: Tip/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tip tip = db.Tips.Find(id);
            if (tip == null)
            {
                return HttpNotFound();
            }
            return View(tip);
        }

        // POST: Tip/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tip tip = db.Tips.Find(id);
            db.Tips.Remove(tip);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Emlaksite/Views/Shared/Arama.cshtml
@using (Html.BeginForm("Search", "Home", FormMethod.Get, new { @class = "navbar-form navbar-left" }))
{
    <div class="form-group">
        <input type="text" class="form-control" name="q" placeholder="Arama">
    </div>
    <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i>Ara</button>
}

Emlaksite/Views/Shared/MahallePartial.cshtml
<option value="">Mahalle seç</option>
@if (ViewBag.mahallelistesi != null)
{

    foreach (var item in ViewBag.mahallelistesi)
    {
        <option value="@item.Value">@item.Text</option>
        
    }

}

Emlaksite/Views/Shared/SemtPartial.cshtml
<option value="">Semt seç</option>
@if (ViewBag.semtlistesi != null)
            {

    foreach (var item in ViewBag.semtlistesi)
    {
        <option value="@item.Value">@item.Text</option>
    }
 }

Emlaksite/Views/Shared/TipPartial.cshtml
<option value="">Tip Seç</option>
@if (ViewBag.tiplistesi!=null)
{
    foreach (var item in ViewBag.tiplistesi)
    {
        <option value="@item.Value">@item.Text</option>
    }
}

Emlaksite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/Content/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous">
    <!--https://fontawesome.com/v6/search?o=r&m=free  bu sayfadan iconları-->
    <!--https://cdnjs.com/libraries/font-awesome Busayfadanda cdn kütüphanesini al-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css" integrity="sha512-5Hs3dF2AEPkpNAR7UiOHba+lRSJNeM2ECkwxUIxC1Q/FLycGTbNapWXB4tP889k5T5Ju8fs4b1P5z/iB4nMfSQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>
<body>
    <header>
        <div class="container">
            <br />
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="/home/Index.html" style="padding-bottom:0px"><img src="~/Content/images/emlak.png" width="50" /></a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                        @Html.Partial("Arama")

                        <ul class="nav navbar-nav navbar-left">
                            <li class="dropdown">
                                @Html.Action("DurumAd2", "Tip")
                                <ul class="dropdown-menu">

                                    @Html.Action("DurumTipSatilikPartial", "Tip")


                                </ul>
                            </li>

                            <li class="dropdown">
                                @Html.Action("DurumAd1", "Tip")
                                <ul class="dropdown-menu">

                                    @Html.Action("DurumTipKiralikPartial", "Tip")
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a href="/Account/Profil" style="color:white">@User.Identity.Name</a></li>
                                <li>
                                    <a href="/Account/Logout">
                                        <button class="btn btn-success"><i class="bi bi-box-arrow-in-right"></i> Çıkış yap</button>
                                    </a>
                                </li>
                            }
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a href="/Account/Login">
                                        <button class="btn btn-success"><i class="bi bi-box-arrow-in-right"></i> Giriş yap</button>
                                    </a>
                                </li>
                            }
                            <li>
                                <a href="/Account/Register"><button class="btn btn-primary"><i class="bi bi-people-fill"></i> Üye ol</button></a>
                            </li>
                            <li>
                                <a href="/Ilan/Create"><button class="btn btn-info"><i class="bi bi-megaphone"></i> İlan ver</button></a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-fluid -->
            </nav>
        </div>
    </header>
    @RenderBody()
    <footer>
        <div class="container">
            <div class="row well" style="background-color:black">
                <div class="col-md-9">
                   
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://localhost:44350/Ilan/Create" style="color:white">İLAN VER</a>
                        </li>

                        <li>
                            <a href="https://localhost:44350/Account/Login" style="color:white">GİRİŞ</a>
                        </li>
                        <li>
                            <a href="https://localhost:44350/Account/Register" style="color:white">ÜYE OL</a>
                        </li>
                        @Html.Action("Durumlist", "Durum")
                    </ul>
                </div>

                <div class="col-md-3">
                    <h5 class="text-muted" style="color:white">SOSYAL MEDYA</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="https://www.facebook.com">
                                <img src="~/Content/images/facebook-icon-png-732.png" width="40" />
                            </a>

                            <a href="https://www.twitter.com" style="color:white">
                                <img src="~/Content/images/twitter.png" width="40" />
                            </a>
                            <a href="https://www.youtube.com">
                                <img src="~/Content/images/youtube.png" width="40" />
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>


</body>
</html>